export { default as PhoneIcon } from './phone.svg';
export { default as LockIcon } from './lock.svg';
export { default as CalendarIcon } from './calendar.svg';
export { default as HomeIcon } from './home.svg';
export { default as SearchIcon } from './search.svg';
export { default as BellIcon } from './bell.svg';
export { default as WalletIcon } from './wallet.svg';
export { default as PlayIcon } from './play.svg';
export { default as AdjustmentsIcon } from './adjustments.svg';
export { default as CloseIcon } from './close.svg';
export { default as ArrowsIcon } from './arrows.svg';
export { default as CameraIcon } from './camera.svg';
export { default as CaseIcon } from './case.svg';
export { default as ChartBarIcon } from './chart-bar.svg';
export { default as ChatIcon } from './chat.svg';
export { default as CheckIcon } from './check.svg';
export { default as ClockIcon } from './Clock.svg';
export { default as CrossIcon } from './cross.svg';
export { default as FireIcon } from './fire.svg';
export { default as GiftIcon } from './gift.svg';
export { default as HeadsetIcon } from './headset.svg';
export { default as LinkIcon } from './link.svg';
export { default as ListIcon } from './List.svg';
export { default as LiveIcon } from './live.svg';
export { default as LoaderIcon } from './loader.svg';
export { default as LocationIcon } from './location.svg';
export { default as MailIcon } from './mail.svg';
export { default as MoonIcon } from './Moon.svg';
export { default as PageIcon } from './page.svg';
export { default as PercentageIcon } from './percentage.svg';
export { default as PlaceholderIcon } from './placeholder.svg';
export { default as RouteIcon } from './route.svg';
export { default as StarEmptyIcon } from './star-empty.svg';
export { default as ThumbDownIcon } from './thumb-down.svg';
export { default as ThumbUpIcon } from './thumb-up.svg';
export { default as TrashIcon } from './trash.svg';
export { default as UserIcon } from './user.svg';
export { default as ArrowBackIcon } from './arrow-back.svg';
export { default as PlusIcon } from './plus.svg';
export { default as InfoIcon } from './info.svg';
export { default as CloseBigIcon } from './close-big.svg';
export { default as InfoCircleIcon } from './info-circle.svg';
export { default as PresentationIcon } from './presentation.svg';
export { default as SoccerFieldIcon } from './soccer-field.svg';
export { default as PlayerPlayIcon } from './player-play.svg';
export { default as ShareIcon } from './share.svg';
export { default as DownloadIcon } from './download.svg';
export { default as VolumeIcon } from './volume.svg';
export { default as PauseIcon } from './player-pause.svg';
export { default as SkullIcon } from './raphael_skull.svg';
export { default as PliersIcon } from './mdi_pliers.svg';
export { default as ExplosionIcon } from './game-icons_mine-explosion.svg';
export { default as CupIcon } from './cup.svg';
export { default as ArrowRightIcon } from './arrowright.svg';
export { default as ArrowsDownUpIcon } from './arrows-down-up.svg';

export * from './footbal';
export * from './sports';
export * from './teams';
export * from './currency';
export * from './tabbar';
export * from './cybersport';
